openapi: 3.0.1
info:
  title: hello
  description: API Definition of hello
  version: 1.0.0
servers:
- url: /default
paths:
  /hello:
    get:
      responses:
        default:
          description: Default response
