openapi: 3.0.1
info:
  title: hello
  description: API Definition of hello
  version: 1.0.0
servers:
- url: /defaulth/defaultt/defaultt/defaultp/default:/default//default//defaultl/defaulto/defaultc/defaulta/defaultl/defaulth/defaulto/defaults/defaultt/default:/default8/default2/default9/default0/default
paths:
  /hello:
    get:
      responses:
        default:
          description: Default response
